# -*- coding: utf-8 -*-
"""Soft_HW4_Q5__07_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NbLtIP-aB-cNemTj-FjHpnB66v8RZwzz
"""

import numpy as np

P = np.array([[1, 1], [1, -1]])
p1 = np.array([[1], [1]])
p2 = np.array([[1], [-1]])
T = np.array([1, -1])

Wh = np.dot(T, P.T)
PPseudoinverse = np.dot(np.linalg.inv(np.dot(P.T, P)), P.T)
W = np.dot(T, np.linalg.pinv(P))

a1h = np.dot(Wh, p1)
a1p = np.dot(W, p1)

print("Wh = ", Wh)
print("PPseudoinverse = ", PPseudoinverse)
print("W = ", W)
print("a1h = ", a1h)
print("a1p = ", a1p)

import numpy as np
import matplotlib.pyplot as plt

p1 = np.array([1,1])
p2 = np.array([1,-1])
plt.plot(p1[0], p1[1], 'ro')
plt.plot(p2[0], p2[1], 'bo')

plt.plot([0,2],[0,0],'k-')
plt.arrow(0,0,0,1,head_width=0.05, head_length=0.1, fc='k', ec='k')

plt.savefig('E710.pdf')
plt.show()